"""
Report generator module - Multi-format report generation.
Supports Markdown, HTML, and JSON output formats.
Zero external dependencies - pure Python implementation.
"""

import json
import os
from datetime import datetime
from typing import Any, Dict, List, Optional

from tablepilot.data_loader import DataTable
from tablepilot.stats_engine import (
    _is_numeric, _numeric_values, correlation_matrix,
    descriptive_stats, detect_outliers_iqr,
)
from tablepilot.visualizer import data_overview_table


def generate_analysis_data(table: DataTable, include_correlation: bool = False,
                           include_outliers: bool = False) -> Dict[str, Any]:
    """Generate comprehensive analysis data for report generation."""
    data = {
        "generated_at": datetime.now().isoformat(),
        "source": table.source,
        "shape": {"rows": table.num_rows, "columns": table.num_columns},
        "columns": [],
    }

    for col in table.columns:
        values = table.column(col)
        stats = descriptive_stats(values)
        col_data = {
            "name": col,
            "statistics": stats,
        }

        if include_outliers and stats["type"] == "numeric":
            col_data["outliers"] = detect_outliers_iqr(values)

        data["columns"].append(col_data)

    if include_correlation:
        data["correlation_matrix"] = correlation_matrix(table)

    return data


def to_markdown(data: Dict[str, Any], title: str = "Data Analysis Report") -> str:
    """Generate a Markdown format report."""
    lines = []

    lines.append(f"# 📊 {title}")
    lines.append("")
    lines.append(f"> Generated by **TablePilot** on {data['generated_at'][:10]}")
    lines.append(f"> Source: `{data['source']}`")
    lines.append(f"> Dataset: **{data['shape']['rows']}** rows × **{data['shape']['columns']}** columns")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Table of Contents
    lines.append("## 📑 Table of Contents")
    lines.append("")
    lines.append("- [📊 Dataset Overview](#-dataset-overview)")
    lines.append("- [📋 Column Analysis](#-column-analysis)")
    if "correlation_matrix" in data:
        lines.append("- [🔗 Correlation Matrix](#-correlation-matrix)")
    lines.append("- [💡 Insights](#-insights)")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Dataset Overview
    lines.append("## 📊 Dataset Overview")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Rows | {data['shape']['rows']:,} |")
    lines.append(f"| Columns | {data['shape']['columns']} |")
    lines.append(f"| Memory (est.) | ~{data['shape']['rows'] * data['shape']['columns'] * 8 / 1024:.1f} KB |")
    lines.append(f"| Generated | {data['generated_at']} |")
    lines.append("")

    # Column Summary Table
    lines.append("### Column Summary")
    lines.append("")
    lines.append("| Column | Type | Non-Null | Null% | Unique |")
    lines.append("|--------|------|----------|-------|--------|")

    for col in data["columns"]:
        stats = col["statistics"]
        cnt = stats["count"]
        uniq = stats["unique"]
        lines.append(
            f"| `{col['name']}` | {stats['type']} | "
            f"{cnt['non_null']:,} | {cnt['null_pct']}% | {uniq['unique']} |"
        )
    lines.append("")

    # Column Analysis
    lines.append("## 📋 Column Analysis")
    lines.append("")

    for col in data["columns"]:
        stats = col["statistics"]
        lines.append(f"### `{col['name']}` ({stats['type']})")
        lines.append("")

        if stats["type"] == "numeric":
            s = stats
            lines.append("| Statistic | Value |")
            lines.append("|-----------|-------|")
            lines.append(f"| Count | {s['count']['non_null']:,} |")
            lines.append(f"| Mean | {s.get('mean', 'N/A')} |")
            lines.append(f"| Median | {s.get('median', 'N/A')} |")
            lines.append(f"| Std Dev | {s.get('std', 'N/A')} |")
            lines.append(f"| Min | {s.get('min', 'N/A')} |")
            lines.append(f"| Max | {s.get('max', 'N/A')} |")
            lines.append(f"| Range | {s.get('range', 'N/A')} |")
            lines.append(f"| Skewness | {s.get('skewness', 'N/A')} |")
            lines.append(f"| Kurtosis | {s.get('kurtosis', 'N/A')} |")
            lines.append(f"| CV | {s.get('cv', 'N/A')} |")
            lines.append("")

            if "percentiles" in s:
                p = s["percentiles"]
                lines.append("**Percentiles:**")
                lines.append("")
                lines.append("| P | Value |")
                lines.append("|---|-------|")
                for pk in ["p1", "p5", "p25", "p50", "p75", "p95", "p99"]:
                    if p.get(pk) is not None:
                        lines.append(f"| {pk.upper()} | {p[pk]} |")
                lines.append("")

            if "outliers" in col:
                out = col["outliers"]
                lines.append(f"**Outliers (IQR):** {out['count']} detected ({out['pct']}%)")
                if out["outliers"]:
                    sample = out["outliers"][:10]
                    lines.append(f"- Sample: {', '.join(str(v) for v in sample)}")
                lines.append("")
        else:
            # Categorical
            if "top_values" in stats:
                lines.append("**Top Values:**")
                lines.append("")
                lines.append("| Value | Count | Percentage |")
                lines.append("|-------|-------|------------|")
                for item in stats["top_values"][:10]:
                    lines.append(f"| `{item['value']}` | {item['count']:,} | {item['pct']}% |")
                lines.append("")

            lines.append(f"**Cardinality:** {stats.get('cardinality', 'N/A')}")
            lines.append("")

    # Correlation Matrix
    if "correlation_matrix" in data and data["correlation_matrix"]:
        lines.append("## 🔗 Correlation Matrix")
        lines.append("")
        corr = data["correlation_matrix"]
        cols = list(corr.keys())
        header = "| | " + " | ".join(f"`{c[:10]}`" for c in cols) + " |"
        sep = "|---|" + "|".join(["---:"] * len(cols)) + "|"
        lines.append(header)
        lines.append(sep)
        for row_name in cols:
            row = f"| `{row_name[:10]}` |"
            for col_name in cols:
                val = corr[row_name].get(col_name)
                if val is None:
                    row += " N/A |"
                else:
                    # Color code
                    if abs(val) >= 0.7:
                        row += f" **{val}** |"
                    elif abs(val) >= 0.4:
                        row += f" *{val}* |"
                    else:
                        row += f" {val} |"
            lines.append(row)
        lines.append("")

    # Insights
    lines.append("## 💡 Insights")
    lines.append("")

    insights = _generate_insights(data)
    for i, insight in enumerate(insights, 1):
        lines.append(f"{i}. {insight}")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Report generated by [TablePilot](https://github.com/gitstq/TablePilot) — Lightweight Tabular Data Intelligent Analysis Engine*")

    return "\n".join(lines)


def to_html(data: Dict[str, Any], title: str = "Data Analysis Report") -> str:
    """Generate an HTML format report."""
    html = []
    html.append(f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
               background: #0d1117; color: #c9d1d9; line-height: 1.6; padding: 2rem; }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        h1 {{ color: #58a6ff; font-size: 2rem; margin-bottom: 0.5rem; }}
        .meta {{ color: #8b949e; margin-bottom: 2rem; }}
        .card {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px;
                 padding: 1.5rem; margin-bottom: 1.5rem; }}
        .card h2 {{ color: #58a6ff; font-size: 1.3rem; margin-bottom: 1rem; }}
        .card h3 {{ color: #79c0ff; font-size: 1.1rem; margin-bottom: 0.8rem; margin-top: 1rem; }}
        table {{ width: 100%; border-collapse: collapse; margin: 0.5rem 0; }}
        th {{ background: #21262d; color: #58a6ff; padding: 0.6rem 1rem; text-align: left;
             border-bottom: 2px solid #30363d; font-size: 0.9rem; }}
        td {{ padding: 0.5rem 1rem; border-bottom: 1px solid #21262d; font-size: 0.9rem; }}
        tr:hover {{ background: #1c2128; }}
        .numeric {{ color: #7ee787; font-family: 'SF Mono', monospace; }}
        .string {{ color: #ffa657; }}
        .badge {{ display: inline-block; padding: 0.2rem 0.6rem; border-radius: 12px;
                  font-size: 0.75rem; font-weight: 600; }}
        .badge-numeric {{ background: #1f6feb33; color: #58a6ff; }}
        .badge-categorical {{ background: #23863633; color: #7ee787; }}
        .insight {{ padding: 0.5rem 0; border-left: 3px solid #58a6ff; padding-left: 1rem; margin: 0.5rem 0; }}
        .footer {{ text-align: center; color: #484f58; margin-top: 2rem; padding-top: 1rem;
                   border-top: 1px solid #21262d; }}
        .strong {{ color: #f0883e; font-weight: 600; }}
        .moderate {{ color: #d29922; }}
        .weak {{ color: #8b949e; }}
    </style>
</head>
<body>
<div class="container">
    <h1>📊 {title}</h1>
    <p class="meta">Generated by <strong>TablePilot</strong> on {data['generated_at'][:10]} |
       Source: <code>{data['source']}</code> |
       {data['shape']['rows']:,} rows × {data['shape']['columns']} columns</p>
""")

    # Overview
    html.append("""    <div class="card">
        <h2>📊 Dataset Overview</h2>
        <table>
            <tr><th>Metric</th><th>Value</th></tr>
""")
    html.append(f"            <tr><td>Rows</td><td class=\"numeric\">{data['shape']['rows']:,}</td></tr>\n")
    html.append(f"            <tr><td>Columns</td><td class=\"numeric\">{data['shape']['columns']}</td></tr>\n")
    html.append(f"            <tr><td>Generated</td><td>{data['generated_at']}</td></tr>\n")
    html.append("        </table>\n    </div>\n")

    # Column Summary
    html.append('    <div class="card">\n        <h2>📋 Column Summary</h2>\n        <table>\n')
    html.append("            <tr><th>Column</th><th>Type</th><th>Non-Null</th><th>Null%</th><th>Unique</th></tr>\n")
    for col in data["columns"]:
        stats = col["statistics"]
        cnt = stats["count"]
        uniq = stats["unique"]
        badge = "numeric" if stats["type"] == "numeric" else "categorical"
        html.append(
            f'            <tr><td><code>{col["name"]}</code></td>'
            f'<td><span class="badge badge-{badge}">{stats["type"]}</span></td>'
            f'<td class="numeric">{cnt["non_null"]:,}</td>'
            f'<td class="numeric">{cnt["null_pct"]}%</td>'
            f'<td class="numeric">{uniq["unique"]}</td></tr>\n'
        )
    html.append("        </table>\n    </div>\n")

    # Column Details
    html.append('    <div class="card">\n        <h2>📋 Column Analysis</h2>\n')
    for col in data["columns"]:
        stats = col["statistics"]
        html.append(f'        <h3><code>{col["name"]}</code> <span class="badge badge-{stats["type"]}">{stats["type"]}</span></h3>\n')

        if stats["type"] == "numeric":
            html.append('        <table><tr><th>Statistic</th><th>Value</th></tr>\n')
            for key, label in [("mean", "Mean"), ("median", "Median"), ("std", "Std Dev"),
                               ("min", "Min"), ("max", "Max"), ("range", "Range"),
                               ("skewness", "Skewness"), ("kurtosis", "Kurtosis"), ("cv", "CV")]:
                val = stats.get(key)
                if val is not None:
                    html.append(f'            <tr><td>{label}</td><td class="numeric">{val}</td></tr>\n')
            html.append("        </table>\n")
        else:
            if "top_values" in stats:
                html.append('        <table><tr><th>Value</th><th>Count</th><th>%</th></tr>\n')
                for item in stats["top_values"][:10]:
                    html.append(f'            <tr><td class="string">{item["value"]}</td>'
                                f'<td class="numeric">{item["count"]:,}</td>'
                                f'<td class="numeric">{item["pct"]}%</td></tr>\n')
                html.append("        </table>\n")

    html.append("    </div>\n")

    # Insights
    insights = _generate_insights(data)
    html.append('    <div class="card">\n        <h2>💡 Key Insights</h2>\n')
    for insight in insights:
        html.append(f'        <div class="insight">{insight}</div>\n')
    html.append("    </div>\n")

    html.append(f"""    <div class="footer">
        <p>Report generated by <strong>TablePilot</strong> — Lightweight Tabular Data Intelligent Analysis Engine</p>
    </div>
</div>
</body>
</html>""")

    return "\n".join(html)


def _generate_insights(data: Dict[str, Any]) -> List[str]:
    """Generate automated insights from analysis data."""
    insights = []

    for col in data["columns"]:
        stats = col["statistics"]
        name = col["name"]

        # High null rate
        if stats["count"]["null_pct"] > 30:
            insights.append(
                f"⚠️ Column `{name}` has a high null rate ({stats['count']['null_pct']}%). "
                f"Consider imputation or removal."
            )

        # Constant column
        if stats["unique"]["unique"] == 1 and stats["count"]["non_null"] > 1:
            insights.append(
                f"📌 Column `{name}` has only one unique value — it provides no information for analysis."
            )

        # High cardinality
        if stats["type"] == "categorical" and stats["unique"].get("unique", 0) > stats["count"]["non_null"] * 0.8:
            insights.append(
                f"🏷️ Column `{name}` has high cardinality ({stats['unique']['unique']} unique values). "
                f"Consider treating as an identifier rather than a categorical feature."
            )

        # Skewed distribution
        if stats["type"] == "numeric":
            skew = stats.get("skewness")
            if skew is not None:
                if abs(skew) > 2:
                    direction = "right" if skew > 0 else "left"
                    insights.append(
                        f"📈 Column `{name}` is heavily {direction}-skewed (skewness={skew}). "
                        f"Consider log transformation."
                    )
                elif abs(skew) > 1:
                    direction = "right" if skew > 0 else "left"
                    insights.append(
                        f"📊 Column `{name}` is moderately {direction}-skewed (skewness={skew})."
                    )

            # Outliers
            if "outliers" in col:
                out = col["outliers"]
                if out["count"] > 0:
                    insights.append(
                        f"🔍 Column `{name}` has {out['count']} outliers ({out['pct']}%) "
                        f"detected by IQR method."
                    )

    if not insights:
        insights.append("✅ Data quality looks good! No significant issues detected.")

    return insights


def save_report(content: str, file_path: str) -> None:
    """Save report content to file."""
    os.makedirs(os.path.dirname(file_path) if os.path.dirname(file_path) else ".", exist_ok=True)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
